[package]
name = "gpg-tui"
version = "0.9.0"
description = "Manage your GnuPG keys with ease!"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/gpg-tui"
homepage = "https://github.com/orhun/gpg-tui"
repository = "https://github.com/orhun/gpg-tui"
keywords = ["gnupg", "gpg", "tui", "key", "management"]
categories = ["command-line-utilities"]
include = ["src/**/*", "assets/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md"]
edition = "2021"
default-run = "gpg-tui"
rust-version = "1.57.0"

[[bin]]
name = "gpg-tui-completions"
path = "src/bin/completions.rs"
test = false

[features]
tui-tests = []
gpg-tests = []

[dependencies]
gpgme = "0.10.0"
tui = "0.19.0"
anyhow = "1.0.62"
chrono = "0.4.22"
unicode-width = "0.1.9"
copypasta-ext = "0.3.9"
colorsys = "0.6.6"
rust-embed = "6.4.0"
shellexpand = "2.1.2"
hex-literal = "0.3.4"
toml = "0.5.9"
dirs-next = "2.0.0"
clap_complete = "3.2.4"
tinytemplate = "1.2.1"

[dependencies.crossterm]
version = "0.25.0"
features = ["serde"]

[dependencies.clap]
version = "3.2.17"
features = ["derive", "env", "wrap_help"]

[dependencies.image]
version = "0.24.3"
default-features = false
features = ["jpeg"]

[dependencies.serde]
version = "1.0.143"
features = ["derive"]

[dev-dependencies]
pretty_assertions = "1.2.1"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "abort"
lto = true
codegen-units = 1

[profile.bench]
opt-level = 3
debug = false
