[general]
  splash = false
  tick_rate = 250
  color = "gray"
  style = "plain"
  file_explorer = "xplr"

[gpg]
  armor = false
  # homedir = "~/.gnupg"
  # outdir = "~/.gnupg/out"
  # default_key = "0xA1B2C3XY"
