name: Docker Automated Builds

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build
        run: docker build -t gpg-tui .
      - name: Tag
        run: |
          docker tag gpg-tui orhunp/gpg-tui:latest
          docker tag gpg-tui docker.pkg.github.com/orhun/gpg-tui/gpg-tui:latest
      - name: Login (Docker Hub)
        run: echo ${{ secrets.DOCKER_TOKEN }} |
          docker login -u orhunp --password-stdin
      - name: Push (Docker Hub)
        run: docker push orhunp/gpg-tui:latest
      - name: Login (Package Registry)
        run: echo ${{ secrets.GITHUB_TOKEN }} |
          docker login -u orhun docker.pkg.github.com --password-stdin
      - name: Push (Package Registry)
        run: docker push docker.pkg.github.com/orhun/gpg-tui/gpg-tui:latest
